// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarehouseX;

#nullable disable

namespace WarehouseX.Migrations
{
    [DbContext(typeof(WarehouseXDbContext))]
    [Migration("20250626111125_SeedAndNullabilityFixes")]
    partial class SeedAndNullabilityFixes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WarehouseX.Models.ExportOrder", b =>
                {
                    b.Property<int>("ExportOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExportOrderId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExportDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ExportOrderId");

                    b.ToTable("ExportOrders");

                    b.HasData(
                        new
                        {
                            ExportOrderId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "BestBuy",
                            Description = "Order for BestBuy",
                            ExportDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ExportOrderId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "GadgetMart",
                            Description = "Order for GadgetMart",
                            ExportDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WarehouseX.Models.ExportOrderItem", b =>
                {
                    b.Property<int>("ExportOrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExportOrderItemId"));

                    b.Property<int>("ExportOrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ExportOrderItemId");

                    b.HasIndex("ExportOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ExportOrderItems");

                    b.HasData(
                        new
                        {
                            ExportOrderItemId = 1,
                            ExportOrderId = 1,
                            ProductId = 1,
                            Quantity = 30
                        },
                        new
                        {
                            ExportOrderItemId = 2,
                            ExportOrderId = 1,
                            ProductId = 2,
                            Quantity = 10
                        },
                        new
                        {
                            ExportOrderItemId = 3,
                            ExportOrderId = 2,
                            ProductId = 3,
                            Quantity = 20
                        });
                });

            modelBuilder.Entity("WarehouseX.Models.ImportOrder", b =>
                {
                    b.Property<int>("ImportOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportOrderId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImportOrderId");

                    b.ToTable("ImportOrders");

                    b.HasData(
                        new
                        {
                            ImportOrderId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Initial stock",
                            ImportDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierName = "Acme Supplies"
                        },
                        new
                        {
                            ImportOrderId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Restock widgets",
                            ImportDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierName = "Widget World"
                        });
                });

            modelBuilder.Entity("WarehouseX.Models.ImportOrderItem", b =>
                {
                    b.Property<int>("ImportOrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportOrderItemId"));

                    b.Property<int>("ImportOrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ImportOrderItemId");

                    b.HasIndex("ImportOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ImportOrderItems");

                    b.HasData(
                        new
                        {
                            ImportOrderItemId = 1,
                            ImportOrderId = 1,
                            ProductId = 1,
                            Quantity = 60
                        },
                        new
                        {
                            ImportOrderItemId = 2,
                            ImportOrderId = 1,
                            ProductId = 3,
                            Quantity = 40
                        },
                        new
                        {
                            ImportOrderItemId = 3,
                            ImportOrderId = 2,
                            ProductId = 1,
                            Quantity = 40
                        },
                        new
                        {
                            ImportOrderItemId = 4,
                            ImportOrderId = 2,
                            ProductId = 2,
                            Quantity = 50
                        });
                });

            modelBuilder.Entity("WarehouseX.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Standard widget",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Widget A",
                            QuantityInStock = 100,
                            SKU = "WIDGET-A"
                        },
                        new
                        {
                            ProductId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Advanced widget",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Widget B",
                            QuantityInStock = 50,
                            SKU = "WIDGET-B"
                        },
                        new
                        {
                            ProductId = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Multi-purpose gadget",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gadget X",
                            QuantityInStock = 75,
                            SKU = "GADGET-X"
                        });
                });

            modelBuilder.Entity("WarehouseX.Models.ExportOrderItem", b =>
                {
                    b.HasOne("WarehouseX.Models.ExportOrder", "ExportOrder")
                        .WithMany("Items")
                        .HasForeignKey("ExportOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseX.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExportOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WarehouseX.Models.ImportOrderItem", b =>
                {
                    b.HasOne("WarehouseX.Models.ImportOrder", "ImportOrder")
                        .WithMany("Items")
                        .HasForeignKey("ImportOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseX.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WarehouseX.Models.ExportOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WarehouseX.Models.ImportOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
