@WarehouseX.Api_HostAddress = http://localhost:5057

### Root
GET {{WarehouseX.Api_HostAddress}}/
Accept: application/json

### Info
GET {{WarehouseX.Api_HostAddress}}/info
Accept: application/json

### DB Ping
GET {{WarehouseX.Api_HostAddress}}/db/ping
Accept: application/json

### Sample IDs (debug)
GET {{WarehouseX.Api_HostAddress}}/debug/sample-ids
Accept: application/json

### Top warehouses (debug)
GET {{WarehouseX.Api_HostAddress}}/debug/top-warehouses?take=5
Accept: application/json

### Inventory adjust (seed)
POST {{WarehouseX.Api_HostAddress}}/inventory/adjust
Content-Type: application/json

{
  "warehouseId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
  "productId": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
  "deltaOnHand": 100
}

### Create order
POST {{WarehouseX.Api_HostAddress}}/orders
Content-Type: application/json

{
  "customerId": "cccccccc-cccc-cccc-cccc-cccccccccccc",
  "warehouseId": "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
  "items": [
    {
      "productId": "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
      "quantity": 2,
      "unitPrice": 10.50
    }
  ]
}

### List orders (deprecated -> 410)
GET {{WarehouseX.Api_HostAddress}}/orders?page=1&pageSize=20
Accept: application/json

### List orders (cursor)
GET {{WarehouseX.Api_HostAddress}}/orders/cursor?warehouseId=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa&pageSize=20
Accept: application/json

### Get order by id
GET {{WarehouseX.Api_HostAddress}}/orders/{{orderId}}
Accept: application/json

### Pick order
POST {{WarehouseX.Api_HostAddress}}/orders/{{orderId}}/pick

### Cancel order
POST {{WarehouseX.Api_HostAddress}}/orders/{{orderId}}/cancel

### Ship order
POST {{WarehouseX.Api_HostAddress}}/orders/{{orderId}}/ship

### Get inventory
GET {{WarehouseX.Api_HostAddress}}/inventory?warehouseId=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa&productId=bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb
Accept: application/json
